"""criar pessoas e imagens faciais

Revision ID: 1dd84101fee5
Revises: 
Create Date: 2026-09-01 15:59:28.318107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dd84101fee5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('identificador', sa.String(length=80), nullable=False),
    sa.Column('data_registro', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pessoas_email'), 'pessoas', ['email'], unique=True)
    op.create_index(op.f('ix_pessoas_identificador'), 'pessoas', ['identificador'], unique=True)
    op.create_table('imagens_faciais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('dados', sa.LargeBinary(), nullable=False),
    sa.Column('tipo_mime', sa.String(length=30), nullable=False),
    sa.Column('largura', sa.Integer(), nullable=False),
    sa.Column('altura', sa.Integer(), nullable=False),
    sa.Column('data_registro', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imagens_faciais_pessoa_id'), 'imagens_faciais', ['pessoa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_imagens_faciais_pessoa_id'), table_name='imagens_faciais')
    op.drop_table('imagens_faciais')
    op.drop_index(op.f('ix_pessoas_identificador'), table_name='pessoas')
    op.drop_index(op.f('ix_pessoas_email'), table_name='pessoas')
    op.drop_table('pessoas')
    # ### end Alembic commands ###
